# OpenAI API Configuration
# Add your OpenAI API key here for AI-powered question generation
# OPENAI_API_KEY = "your_openai_api_key_here"

# Note: For production use, consider using environment variables
# or a proper secrets management system instead of storing keys here